### ISSUE TITLE
Unificar respuesta JSON de la API Rest

### ISSUE THREAD

**Issue by edittler** [ezeperez26/fiuba-campus-movil-ws#1]
Unificar los JSON de la API de la siguiente forma:

``` json
{
  "result": "<result>",
  "message": "<message>",
  "otherObjectKey": "otherObject" 
}
```

Los valores de `result` pueden ser:
- ok: La petición fue procesada correctamente
- error: Ocurrió un error

@MarcoLotto fijate si hace falta agregar otros valores de `result`.

**Comment by ezeperez26** [comment]
Ya fueron corregidas las apis existentes y se empezó a utilizar dicho formato en las nuevas apis.
